= THIS PROJECT IS NO LONGER MAINTAINED.

I hope to someday make a better version.

Problems with this:

. No moderation
. Possible panic if two people use `/delroom` at the same time
. No blocking
. No account-type things (have to reset username everytime with no way to verify it)

And more.

= tcparle

Chat over TCP. Name is TCP + "parle", which is French for talk.

You can connect with `telnet`:

[source,bash]
----
$ telnet $HOST:$PORT
----

Currently, it's built entirely with just the standard library.

== Commands

* `/room [room]`: Join a room. Rooms will be created if they do not exist. If
  no arguments are given, it will print your current room.
* `/rooms`: List all rooms.
* `/delroom [room]`: Deletes a room if it is empty.
* `/nick [name]`: Change your display name.
* `/quit`: Leave the chat

If you don't specify a command, whatever you type will be sent to everyone in
your room.

== Roadmap

* Color the usernames
* Add a `/help` command
* Validate room names
* Add a prompt with this format: `[user]:`
* Make a `/typing` command that gives a typing test and broadcasts user's
  results

== License

This project uses the Unlicense. See https://unlicense.org for more info.
